package state;

public enum BotStates {
    NEWS_WANTED,
    COUNTRY_FOR_NEWS_WANTED,
    WEATHER_WANTED,
    FAQ_WANTED,
    GAMES_WANTED,
    WEATHER_DONE,
    GAMES_DONE,
    NEWS_DONE,
    INITIAL,
    NOT_IMPLEMENTED
}
